import numpy as np
from scipy.special import erfc, erfcx

def get_2d_ewald_energy(params, k_max=12, tol=1e-8):
    """
    Computes the total electrostatic energy of a 2D+h slab system 
    sandwiched between two dielectric interfaces using a 2D Ewald method.
    """
    positions = np.asarray(params["positions"], dtype=np.float64)
    charges = np.asarray(params["charges"], dtype=np.float64)
    lz = float(params["lz"])
    lx = float(params["lx"])
    ly = float(params["ly"])
    prefactor = float(params["prefactor"])
    
    # Delta terms: bot (z=0), top (z=lz)
    delta_b = float(params["delta_mid_bot"])
    delta_t = float(params["delta_mid_top"])
    delta_prod = delta_b * delta_t

    N_atoms = len(charges)
    A = lx * ly

    # Choose an optimal Ewald splitting parameter alpha
    alpha = 5.0 / min(lx, ly)

    # Automatically estimate image cutoff bounds based on tolerance
    if abs(delta_prod) > 1e-10:
        n_img_max = int(np.ceil(-np.log(tol) / (2.0 * alpha * lz))) + 1
        n_img_max = max(4, min(n_img_max, 40))
    else:
        n_img_max = 2

    # Vectorized helper for the Ewald reciprocal layer function h(k, z)
    def _h_vec(k, z_arr):
        u_plus = k / (2.0 * alpha) + alpha * z_arr
        u_minus = k / (2.0 * alpha) - alpha * z_arr
        # Guard against large arguments in standard exp
        arg_exp = - (k / (2.0 * alpha))**2 - (alpha * z_arr)**2
        # Mask out values that cause deep underflow
        mask = arg_exp > -700.0
        res = np.zeros_like(z_arr)
        if np.any(mask):
            res[mask] = np.exp(arg_exp[mask]) * (erfcx(u_plus[mask]) + erfcx(u_minus[mask]))
        return res

    # 1D Ewald k=0 integration function: g(z) = z * erf(alpha*z) + exp(-alpha^2*z^2)/(alpha*sqrt(pi))
    def _g_vec(z_arr):
        abs_z = np.abs(z_arr)
        return abs_z * (1.0 - erfc(alpha * abs_z)) + np.exp(-(alpha * z_arr)**2) / (alpha * np.sqrt(np.pi))

    # ------------------------------------------------------------------
    # 1. Real Space Sum (with periodic images & multi-dielectric reflections)
    # ------------------------------------------------------------------
    E_real = 0.0
    n_real = 5  # Typical real-space cell replication index for alpha window

    # Pre-generate image configuration tables (charge factors and z-shifts)
    # Track the 4 distinct geometric reflection sequences generated by the two boundaries
    image_series = [] # entries: (q_factor, z_image_expression_type, nz_multiplier)
    
    for nz in range(-n_img_max, n_img_max + 1):
        # Sequence 1: Even reflections starting bottom or top
        q_even = delta_prod ** abs(nz)
        image_series.append((q_even, 'even', nz))
        
        # Sequence 2: Odd reflections from Bottom boundary
        q_odd_b = delta_b * (delta_prod ** abs(nz)) if nz >= 0 else delta_b * (delta_prod ** abs(nz + 1))
        image_series.append((q_odd_b, 'odd_b', nz))
        
        # Sequence 3: Odd reflections from Top boundary
        q_odd_t = delta_t * (delta_prod ** abs(nz)) if nz >= 0 else delta_t * (delta_prod ** abs(nz - 1))
        image_series.append((q_odd_t, 'odd_t', nz))

    # Nested loop processing positions
    for nx in range(-n_real, n_real + 1):
        for ny in range(-n_real, n_real + 1):
            shift_x = nx * lx
            shift_y = ny * ly
            
            for i in range(N_atoms):
                xi, yi, zi = positions[i]
                qi = charges[i]
                
                for j in range(N_atoms):
                    xj, yj, zj = positions[j]
                    qj = charges[j]
                    
                    dx = xj - xi + shift_x
                    dy = yj - yi + shift_y
                    r2_base = dx*dx + dy*dy
                    is_primary = False
                    z_img = 0

                    for q_fac, seq_type, nz in image_series:
                        if abs(q_fac) < 1e-14: 
                            continue
                            
                        # Resolve explicit image positions based on analytical reflections
                        if seq_type == 'even':
                            z_img = zj + 2.0 * nz * lz
                            is_primary = (nx == 0 and ny == 0 and nz == 0 and i == j)
                        elif seq_type == 'odd_b':
                            z_img = -zj + 2.0 * nz * lz
                            is_primary = False
                        elif seq_type == 'odd_t':
                            z_img = 2.0 * lz - zj + 2.0 * nz * lz
                            is_primary = False
                        
                        if is_primary:
                            continue
                            
                        dz = z_img - zi
                        r = np.sqrt(r2_base + dz*dz)
                        if r > 1e-12:
                            E_real += qi * qj * q_fac * erfc(alpha * r) / r

    E_real *= 0.5

    # ------------------------------------------------------------------
    # 2. Reciprocal Space Sum (k != 0)
    # ------------------------------------------------------------------
    E_recip = 0.0
    fac_k = 2.0 * np.pi / lx
    fac_l = 2.0 * np.pi / ly

    for mx in range(-k_max, k_max + 1):
        for my in range(-k_max, k_max + 1):
            if mx == 0 and my == 0:
                continue
                
            kx = mx * fac_k
            ky = my * fac_l
            k = np.sqrt(kx*kx + ky*ky)
            
            # Formulate structure factor blocks cleanly across coordinates
            for i in range(N_atoms):
                xi, yi, zi = positions[i]
                qi = charges[i]
                
                for j in range(N_atoms):
                    xj, yj, zj = positions[j]
                    qj = charges[j]
                    
                    cos_drho = np.cos(kx * (xj - xi) + ky * (yj - yi))
                    q_ij = qi * qj * cos_drho
                    
                    # Compute spatial layer interactions
                    term_even = np.zeros(1)
                    term_odd_b = np.zeros(1)
                    term_odd_t = np.zeros(1)
                    
                    for q_fac, seq_type, nz in image_series:
                        if abs(q_fac) < 1e-12:
                            continue
                        
                        # Apply analytical exponential damping corrections matching the ELC layout
                        exp_damping = np.exp(-2.0 * k * abs(nz) * lz)
                        
                        if seq_type == 'even':
                            term_even += q_fac * exp_damping * _h_vec(k, np.array([zj - zi + 2.0 * nz * lz]))
                        elif seq_type == 'odd_b':
                            term_odd_b += q_fac * exp_damping * _h_vec(k, np.array([-zj - zi + 2.0 * nz * lz]))
                        elif seq_type == 'odd_t':
                            term_odd_t += q_fac * exp_damping * _h_vec(k, np.array([2.0 * lz - zj - zi + 2.0 * nz * lz]))
                            
                    E_recip += q_ij * (term_even[0] + term_odd_b[0] + term_odd_t[0]) / k

    E_recip *= 0.5 * (np.pi / A)

    # ------------------------------------------------------------------
    # 3. M=0 / K=0 Background Geometry Boundary Term
    # ------------------------------------------------------------------
    E_k0 = 0.0
    for i in range(N_atoms):
        zi, qi = positions[i, 2], charges[i]
        for j in range(N_atoms):
            zj, qj = positions[j, 2], charges[j]
            q_ij = qi * qj
            
            v_k0 = 0.0
            for q_fac, seq_type, nz in image_series:
                if abs(q_fac) < 1e-14:
                    continue
                if seq_type == 'even':
                    v_k0 += q_fac * _g_vec(np.array([zj - zi + 2.0 * nz * lz]))[0]
                elif seq_type == 'odd_b':
                    v_k0 += q_fac * _g_vec(np.array([-zj - zi + 2.0 * nz * lz]))[0]
                elif seq_type == 'odd_t':
                    v_k0 += q_fac * _g_vec(np.array([2.0 * lz - zj - zi + 2.0 * nz * lz]))[0]
                    
            E_k0 += q_ij * v_k0

    E_k0 *= - (np.pi / A)

    # ------------------------------------------------------------------
    # 4. Total Generalized Self-Energy Corrections
    # ------------------------------------------------------------------
    # Part A: Classical bulk charge self interaction
    E_self_bulk = - (alpha / np.sqrt(np.pi)) * np.sum(charges ** 2)
    
    # Part B: Dielectric Self-Image interactions (charge interacting with its own boundary reflections)
    E_self_images = 0.0
    d_self = 0
    for i in range(N_atoms):
        zi, qi = positions[i, 2], charges[i]
        for q_fac, seq_type, nz in image_series:
            if seq_type == 'even' and nz == 0:
                continue # Omit primary target itself
                
            if seq_type == 'even':
                d_self = 2.0 * nz * lz
            elif seq_type == 'odd_b':
                d_self = -2.0 * zi + 2.0 * nz * lz
            elif seq_type == 'odd_t':
                d_self = 2.0 * lz - 2.0 * zi + 2.0 * nz * lz
                
            abs_d = abs(d_self)
            if abs_d > 1e-12:
                E_self_images += (qi ** 2) * q_fac * erfc(alpha * abs_d) / abs_d
            else:
                # Limit value for touching image configurations
                E_self_images += (qi ** 2) * q_fac * (-2.0 * alpha / np.sqrt(np.pi))

    E_self = E_self_bulk + 0.5 * E_self_images

    # Combine all items
    E_total = E_real + E_recip + E_k0 + E_self
    return prefactor * E_total